jupyter_book_task:
  environment:
    GH_TOKEN: ENCRYPTED[!bbf36430e8ba7b6a1dc3ada56ab696fbc35cb89d1d9efd3ce370d1fbc101b670c79fe815b9972d66a9d2993ed7f449eb!]
  auto_cancellation: true
  container:
    dockerfile: Dockerfile
    cpu: 4
    memory: 16G
    use_in_memory_disk: true
  notebook_script: |
    find . -type f -name "*.ipynb" -print0 | parallel -0 -j4 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --allow-errors --inplace {}
    mkdir -p out
    cp *.ipynb out/
  pages_script: |
    if [[ $CIRRUS_BRANCH == "main" ]]; then
      ghp-import -n out
      git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
    fi
