jupyter_book_task:
  environment:
    GH_TOKEN: ENCRYPTED[!bbf36430e8ba7b6a1dc3ada56ab696fbc35cb89d1d9efd3ce370d1fbc101b670c79fe815b9972d66a9d2993ed7f449eb!]
  auto_cancellation: true
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 16G
    use_in_memory_disk: true
  notebook_script: |
    parallel -j4 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --allow-errors --inplace {} ::: docs/*.ipynb
  website_script: |
    jupyter-book build --keep-going -v docs/
  pages_script: |
    if [[ $CIRRUS_BRANCH == "main" ]]; then
      git config --global user.name "Wen-Wei Tseng"
      git config --global user.email sosiristseng@gmail.com
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -n -p -f docs/_build/html
    fi
