jupyter_book_task:
  # Only on the main branch, tags, and PR
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  env:
    JOBS: 8
    TIMEOUT: 1000
    GH_TOKEN: ENCRYPTED[c10d05d3caf07e913a481bb301a070e3db1167fe227826d1f7c2348093fbfecd1f73e88a442c3402bde3ecb541b5d4f3]
  auto_cancellation: true
  container:
    dockerfile: cirrus.Dockerfile
    cpu: 4
    memory: 16G
    greedy: true
  notebook_script: |
    parallel --joblog /tmp/log -j${JOBS} jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=${TIMEOUT} --execute --allow-errors --inplace {} ::: docs/*.ipynb
    cat /tmp/log
  build_script: |
    jupyter-book build docs/ --warningiserror --keep-going -v
  # Requires a repo scope access `GH_TOKEN` PAT to push
  pages_script: |
    if [[ $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH ]]; then
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -n -p -f docs/_build/html
    fi
